package cn.chen.demo_greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.chen.demo_greendao.entity.User;
import cn.chen.demo_greendao.entity.Person;
import cn.chen.demo_greendao.entity.Normal;

import cn.chen.demo_greendao.dao.UserDao;
import cn.chen.demo_greendao.dao.PersonDao;
import cn.chen.demo_greendao.dao.NormalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig normalDaoConfig;

    private final UserDao userDao;
    private final PersonDao personDao;
    private final NormalDao normalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        normalDaoConfig = daoConfigMap.get(NormalDao.class).clone();
        normalDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        normalDao = new NormalDao(normalDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Person.class, personDao);
        registerDao(Normal.class, normalDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        personDaoConfig.getIdentityScope().clear();
        normalDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public NormalDao getNormalDao() {
        return normalDao;
    }

}
